In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

###**Manipulação de Colunas**

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.Survived

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [7]:
df.rename(columns={
    'PassengerId': 'ID_Passageniro', 
    'Survived': 'Sobreviveu', 
    'Pclass': 'Classe', 
    'Name': 'Nome', 
    'Sex': 'Sexo', 
    'Age': 'Idade', 
    'SibSp': 'Membros_Familia',
    'Parch': 'Pais_Filhos_a_Bordo',
    'Ticket': 'Bilhete', 
    'Fare': 'Valor_Passagem', 
    'Cabin':'Cabine', 
    'Embarked': 'Portao_Embarque'
}, inplace=True)
df.head(3)

,ID_Passageniro,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [8]:
dados = df.copy()
dados.head(3)

,ID_Passageniro,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [9]:
dados.drop(['ID_Passageniro'], axis=1, inplace=True)
dados.head(3)

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
dados[['Sobreviveu', 'Classe']]

     Sobreviveu  Classe
0             0       3
1             1       1
2             1       3
3             1       1
4             0       3
..          ...     ...
886           0       2
887           1       1
888           0       3
889           1       1
890           0       3

[891 rows x 2 columns]

###**Loc**

In [11]:
#Número das linhas (Valor incial até o valor final) e número das colunas (passar uma lista)
dados.loc[15:35, ['Sobreviveu', 'Nome', 'Idade']]

    Sobreviveu                                               Nome  Idade
15           1                   Hewlett, Mrs. (Mary D Kingcome)    55.0
16           0                               Rice, Master. Eugene    2.0
17           1                       Williams, Mr. Charles Eugene    NaN
18           0  Vander Planke, Mrs. Julius (Emelia Maria Vande...   31.0
19           1                            Masselmani, Mrs. Fatima    NaN
20           0                               Fynney, Mr. Joseph J   35.0
21           1                              Beesley, Mr. Lawrence   34.0
22           1                        McGowan, Miss. Anna "Annie"   15.0
23           1                       Sloper, Mr. William Thompson   28.0
24           0                      Palsson, Miss. Torborg Danira    8.0
25           1  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   38.0
26           0                            Emir, Mr. Farred Chehab    NaN
27           0                     Fortune, Mr. Charles Alexander   19.0
28           1                      O'Dwyer, Miss. Ellen "Nellie"    NaN
29           0                                Todoroff, Mr. Lalio    NaN
30           0                           Uruchurtu, Don. Manuel E   40.0
31           1     Spencer, Mrs. William Augustus (Marie Eugenie)    NaN
32           1                           Glynn, Miss. Mary Agatha    NaN
33           0                              Wheadon, Mr. Edward H   66.0
34           0                            Meyer, Mr. Edgar Joseph   28.0
35           0                     Holverson, Mr. Alexander Oskar   42.0

In [12]:
dados.loc[:500, ['Sobreviveu', 'Nome', 'Idade']]

     Sobreviveu                                               Nome  Idade
0             0                            Braund, Mr. Owen Harris   22.0
1             1  Cumings, Mrs. John Bradley (Florence Briggs Th...   38.0
2             1                             Heikkinen, Miss. Laina   26.0
3             1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   35.0
4             0                           Allen, Mr. William Henry   35.0
..          ...                                                ...    ...
496           1                     Eustis, Miss. Elizabeth Mussey   54.0
497           0                    Shellard, Mr. Frederick William    NaN
498           0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   25.0
499           0                                 Svensson, Mr. Olof   24.0
500           0                                   Calic, Mr. Petar   17.0

[501 rows x 3 columns]

###**Iloc**

In [13]:
#
dados.iloc[5:15, 1:4]

    Classe                                               Nome    Sexo
5        3                                   Moran, Mr. James    male
6        1                            McCarthy, Mr. Timothy J    male
7        3                     Palsson, Master. Gosta Leonard    male
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female
10       3                    Sandstrom, Miss. Marguerite Rut  female
11       1                           Bonnell, Miss. Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female

###**Seleção por condição**

In [14]:
dados.loc[dados['Classe'] == 1]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [15]:
dados.loc[dados['Sexo'] == 'female']

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [16]:
dados.loc[dados['Idade'] < 18]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
7,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
850,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S
852,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
853,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
869,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

In [17]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male') & (dados['Sobreviveu'] != 0)]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
78,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
125,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C
165,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S
183,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
193,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
204,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.00,0,0,A/5 3540,8.0500,NaN,S
220,1,3,"Sunderland, Mr. Victor Francis",male,16.00,0,0,SOTON/OQ 392089,8.0500,NaN,S
261,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S
305,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
340,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
348,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S
407,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S
445,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
489,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S
549,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S
550,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
751,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S
755,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
788,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S
802,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
803,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
827,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
869,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

In [18]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male')][['Nome', 'Portao_Embarque']]

                                        Nome Portao_Embarque
7             Palsson, Master. Gosta Leonard               S
16                      Rice, Master. Eugene               Q
50                Panula, Master. Juha Niilo               S
59        Goodwin, Master. William Frederick               S
63                     Skoog, Master. Harald               S
..                                       ...             ...
834                   Allum, Mr. Owen George               S
841                 Mudd, Mr. Thomas Charles               S
844                      Culumovic, Mr. Jeso               S
850  Andersson, Master. Sigvard Harald Elias               S
869          Johnson, Master. Harold Theodor               S

[71 rows x 2 columns]

In [19]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male') | (dados['Sexo'] == 'female')][['Nome', 'Portao_Embarque']]

                                                  Nome Portao_Embarque
1    Cumings, Mrs. John Bradley (Florence Briggs Th...               C
2                               Heikkinen, Miss. Laina               S
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)               S
7                       Palsson, Master. Gosta Leonard               S
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)               S
..                                                 ...             ...
880       Shelley, Mrs. William (Imanita Parrish Hall)               S
882                       Dahlberg, Miss. Gerda Ulrika               S
885               Rice, Mrs. William (Margaret Norton)               Q
887                       Graham, Miss. Margaret Edith               S
888           Johnston, Miss. Catherine Helen "Carrie"               S

[385 rows x 2 columns]

###**Filtros por srings**

In [20]:
dados[dados['Nome'].str.contains('Mr')]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
dados[dados['Nome'].str.len()>50]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
18,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
25,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
41,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
85,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
142,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.0,1,0,STON/O2. 3101279,15.8500,NaN,S
307,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,1,0,PC 17758,108.9000,C65,C
319,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.0,1,1,16966,134.5000,E34,C
323,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.0,1,1,248738,29.0000,NaN,S
383,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.0,1,0,113789,52.0000,NaN,S
394,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
423,0,3,"Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria ...",female,28.0,1,1,347080,14.4000,NaN,S
427,1,2,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.0,0,0,250655,26.0000,NaN,S
432,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.0,1,0,SC/AH 3085,26.0000,NaN,S
518,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S
556,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0,1,0,11755,39.6000,A16,C
581,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C
600,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
608,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",female,22.0,1,2,SC/Paris 2123,41.5792,NaN,C
610,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,347082,31.2750,NaN,S
670,1,2,"Brown, Mrs. Thomas William Solomon (Elizabeth ...",female,40.0,1,1,29750,39.0000,NaN,S
759,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,B77,S
779,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
799,0,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S
862,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S

In [22]:
dados[dados['Membros_Familia'].isin([1])]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
869,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

###**Filtro por query**

In [26]:
dados.query('Sobreviveu == 1')[['Nome', 'Idade']].head(3)

                                                Nome  Idade
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   38.0
2                             Heikkinen, Miss. Laina   26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   35.0

In [27]:
dados.query('Sexo == "female"').head(3)

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [28]:
#dados.loc[(dados['Idade']<=18) & (dados['Sexo'] == 'male') | (dados['Sexo'] == 'female')][['Nome', 'Portao_Embarque']]
dados.query('Idade >= 40 & Sexo == "female"').head(3)

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.550,C103,S
15,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.000,NaN,S
40,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.475,NaN,S

In [29]:
idade = 20
dados.query('Idade >= @idade').head(3)

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

###**Trabalhando com datas**

In [30]:
!pip install yfinance

Requirement already satisfied: yfinance in /home/leandro/anaconda3/lib/python3.13/site-packages (1.5.1)
Requirement already satisfied: pandas>=1.3.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: peewee>=3.16.2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (4.1.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: rich in /home/leandro/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: pycparser in /home/leandro/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /home/leandro/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/leandro/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/leandro/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /home/leandro/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.0)

In [31]:
import yfinance as y

In [32]:
petrobras = y.download('petr4.sa', period='3y')

[*********************100%***********************]  1 of 1 completed

In [33]:
petrobras.head(3)

Price           Close       High        Low       Open    Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA  PETR4.SA
Date
2023-10-30  23.258566  23.682895  23.112702  23.590073  31346900
2023-10-31  23.033142  23.324868  22.867388  23.212154  36965200
2023-11-01  23.285084  23.563551  23.139222  23.218783  46335300

In [34]:
petrobras.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 747 entries, 2023-10-30 to 2026-10-27
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Close, PETR4.SA)   747 non-null    float64
 1   (High, PETR4.SA)    747 non-null    float64
 2   (Low, PETR4.SA)     747 non-null    float64
 3   (Open, PETR4.SA)    747 non-null    float64
 4   (Volume, PETR4.SA)  747 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 35.0 KB

In [35]:
petrobras.index

DatetimeIndex(['2023-10-30', '2023-10-31', '2023-11-01', '2023-11-03',
               '2023-11-06', '2023-11-07', '2023-11-08', '2023-11-09',
               '2023-11-10', '2023-11-13',
               ...
               '2026-10-14', '2026-10-15', '2026-10-16', '2026-10-19',
               '2026-10-20', '2026-10-21', '2026-10-22', '2026-10-23',
               '2026-10-26', '2026-10-27'],
              dtype='datetime64[ns]', name='Date', length=747, freq=None)

In [39]:
petrobras.loc[petrobras.index == '2023-11-06']

Price           Close       High        Low       Open    Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA  PETR4.SA
Date
2023-11-06  23.543657  23.954728  23.543657  23.696153  33583600

In [40]:
petrobras.loc[petrobras.index >= '2023-11-06']

Price           Close       High        Low       Open     Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA
Date
2023-11-06  23.543657  23.954728  23.543657  23.696153   33583600
2023-11-07  23.152477  23.483985  22.980095  23.251931   48919900
2023-11-08  22.655218  23.072918  22.482835  22.940315   59742900
2023-11-09  23.125965  23.304979  22.781197  22.874019   56231100
2023-11-10  23.019878  23.245304  22.880643  22.980097   40004800
...               ...        ...        ...        ...        ...
2026-10-21  57.750000  58.680000  57.750000  58.209999   37151500
2026-10-22  57.830002  58.599998  57.009998  58.389999   39860200
2026-10-23  58.680000  59.790001  58.009998  58.099998   58347500
2026-10-26  53.880001  54.230000  51.169998  51.200001  141338400
2026-10-27  52.790001  53.700001  52.660000  53.599998   80592800

[743 rows x 5 columns]

In [44]:
petrobras.loc[petrobras.index.year == 2026]

Price           Close       High        Low       Open     Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA
Date
2026-01-02  28.875490  29.110556  28.546399  29.110556   21625200
2026-01-05  28.395956  28.931906  27.954031  28.866088   48211400
2026-01-06  27.869408  28.612217  27.850604  28.555801   38095000
2026-01-07  28.048058  28.048058  27.765979  27.897616   28132900
2026-01-08  28.395956  28.527592  28.010448  28.123279   34125800
...               ...        ...        ...        ...        ...
2026-10-21  57.750000  58.680000  57.750000  58.209999   37151500
2026-10-22  57.830002  58.599998  57.009998  58.389999   39860200
2026-10-23  58.680000  59.790001  58.009998  58.099998   58347500
2026-10-26  53.880001  54.230000  51.169998  51.200001  141338400
2026-10-27  52.790001  53.700001  52.660000  53.599998   80592800

[205 rows x 5 columns]

In [46]:
petrobras.loc[petrobras.index.month == 3]

Price           Close       High        Low       Open    Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA  PETR4.SA
Date
2024-03-01  27.683987  28.145615  27.656426  27.801115  31248500
2024-03-04  27.615086  28.076714  27.573745  27.745994  21988000
2024-03-05  27.532412  27.814901  27.291263  27.628871  30293300
2024-03-06  28.138725  28.138725  27.635756  27.697766  45481000
2024-03-07  27.828678  28.207627  27.752888  28.000928  50199800
...               ...        ...        ...        ...       ...
2026-03-25  44.662510  44.709522  43.534193  43.722247  40532900
2026-03-26  45.151447  45.574567  44.681316  44.756535  59986800
2026-03-27  46.458416  46.486623  45.254880  45.602776  54170900
2026-03-30  46.702881  47.661950  46.533637  46.778104  51454300
2026-03-31  45.762619  47.530315  44.803553  47.078989  78931700

[61 rows x 5 columns]

In [47]:
petrobras.loc[petrobras.index.day == 15]

Price           Close       High        Low       Open     Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA
Date
2023-12-15  24.390575  24.659285  24.114975  24.307894   56570100
2024-01-15  26.581591  26.609149  26.085510  26.175081   13818300
2024-02-15  29.144665  29.144665  28.145615  28.255855   33246400
2024-03-15  25.024450  25.114021  24.762630  25.010670   59362500
2024-04-15  27.084560  27.181020  26.616041  26.829629   28692000
2024-05-15  28.393980  28.697145  27.728495  27.802437  131281100
2024-07-15  29.278997  29.453911  29.050850  29.126898   22969200
2024-08-15  29.157312  29.324622  28.898745  28.936769   33409000
2024-10-15  29.251913  29.259733  28.985986  29.103305   28204600
2025-01-15  31.484201  31.509530  31.070490  31.180250   32512700
2025-04-15  26.173508  26.908055  26.156621  26.789851   58276900
2025-05-15  27.573490  27.763831  27.331237  27.426408   32468300
2025-07-15  28.475691  28.858932  28.350914  28.734156   18688300
2025-08-15  26.889254  26.933816  26.506012  26.826866   55416100
2025-09-15  28.665960  28.757107  28.310483  28.529237   21978400
2025-10-15  27.116446  27.499266  27.043527  27.389888   40261000
2025-12-15  28.893829  29.076124  28.793566  28.875599   31898900
2026-01-15  29.890976  30.022612  29.561883  29.618299   26456600
2026-04-15  44.088955  45.226673  43.938513  45.085636   61852100
2026-05-15  43.356884  43.423631  42.889654  43.280600   59380500
2026-06-15  37.871323  38.705148  37.871323  38.627584   54174000
2026-07-15  39.354759  39.558368  39.005714  39.180237   25608800
2026-09-15  50.430000  50.700001  49.029999  49.060001   46559600
2026-10-15  57.360001  58.090000  57.090000  57.599998   37576500

In [48]:
petrobras.loc[petrobras.index.quarter == 3]

Price           Close       High        Low       Open    Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA  PETR4.SA
Date
2024-07-01  29.377857  29.476719  29.035635  29.134500  24963500
2024-07-02  29.286594  29.735286  29.233360  29.529955  33346200
2024-07-03  28.777069  29.499538  28.716228  29.431094  38509400
2024-07-04  28.381613  28.868328  28.229514  28.822700  32698800
2024-07-05  28.533710  28.632575  28.221908  28.480476  32758800
...               ...        ...        ...        ...       ...
2026-09-24  49.259998  50.240002  49.189999  49.700001  34675400
2026-09-25  48.070000  48.869999  47.919998  48.799999  34445400
2026-09-28  48.720001  49.270000  48.279999  48.560001  46903600
2026-09-29  49.099998  49.099998  47.889999  48.119999  24110900
2026-09-30  49.119999  50.029999  49.119999  49.799999  31859600

[197 rows x 5 columns]

In [49]:
petrobras.loc[(petrobras.index.year == 2026) & (petrobras.index.month == 3)]

Price           Close       High        Low       Open     Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA
Date
2026-03-02  38.673035  39.049138  38.099473  38.832878   83817000
2026-03-03  38.503788  39.491064  38.315735  39.208986   93893800
2026-03-04  38.080669  38.710644  37.544720  38.503789   50915600
2026-03-05  38.259319  38.334542  37.591733  38.108877   53107600
2026-03-06  39.641506  40.544158  38.945710  39.397039   87228000
2026-03-09  40.581772  41.625465  40.121041  40.666396  107124400
2026-03-10  40.365509  40.525352  39.519271  39.782547   56706200
2026-03-11  42.123802  42.199025  40.647589  40.666395   73234300
2026-03-12  42.311859  43.336747  41.559649  42.678561   86124400
2026-03-13  42.001568  42.631546  41.644270  41.945154   42520400
2026-03-16  43.120483  43.242719  42.123803  42.199026   40474100
2026-03-17  43.609417  44.436846  43.064062  43.111075   51025600
2026-03-18  44.192379  44.333420  43.769260  43.910301   55074700
2026-03-19  43.985523  45.254881  43.900899  44.380436   84865000
2026-03-20  42.941826  44.427444  42.236628  43.994923   78125700
2026-03-23  43.280327  43.421368  41.672477  41.766502   65252400
2026-03-24  44.446255  45.085634  43.600016  43.628227   57455300
2026-03-25  44.662510  44.709522  43.534193  43.722247   40532900
2026-03-26  45.151447  45.574567  44.681316  44.756535   59986800
2026-03-27  46.458416  46.486623  45.254880  45.602776   54170900
2026-03-30  46.702881  47.661950  46.533637  46.778104   51454300
2026-03-31  45.762619  47.530315  44.803553  47.078989   78931700

In [50]:
petrobras['dia_semana'] = petrobras.index.day_name()
petrobras.head(3)

Price           Close       High        Low       Open    Volume dia_semana
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA  PETR4.SA
Date
2023-10-30  23.258566  23.682895  23.112702  23.590073  31346900     Monday
2023-10-31  23.033142  23.324868  22.867388  23.212154  36965200    Tuesday
2023-11-01  23.285084  23.563551  23.139222  23.218783  46335300  Wednesday

###**Dados Faltantes**

In [51]:
dados_1 = dados.copy()
dados_2 = dados.copy()
dados_3 = dados.copy()

In [ ]:
dados.isnull().sum() #True = 1 e False = 0

Sobreviveu               0
Classe                   0
Nome                     0
Sexo                     0
Idade                  177
Membros_Familia          0
Pais_Filhos_a_Bordo      0
Bilhete                  0
Valor_Passagem           0
Cabine                 687
Portao_Embarque          2
dtype: int64

In [54]:
dados.loc[dados['Idade'].isnull()]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [55]:
dados.loc[dados['Cabine'].isnull()]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [56]:
dados_1.dropna(inplace=True)

In [59]:
dados_1.shape

(183, 11)

In [60]:
dados_1.isnull().sum()

Sobreviveu             0
Classe                 0
Nome                   0
Sexo                   0
Idade                  0
Membros_Familia        0
Pais_Filhos_a_Bordo    0
Bilhete                0
Valor_Passagem         0
Cabine                 0
Portao_Embarque        0
dtype: int64

In [61]:
meida_idade = dados_2['Idade'].mean()
meida_idade

np.float64(29.69911764705882)

In [63]:
dados_2['Idade'].fillna(30, inplace=True)
dados_2.isnull().sum()

/tmp/ipykernel_16627/739616551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados_2['Idade'].fillna(30, inplace=True)

Sobreviveu               0
Classe                   0
Nome                     0
Sexo                     0
Idade                    0
Membros_Familia          0
Pais_Filhos_a_Bordo      0
Bilhete                  0
Valor_Passagem           0
Cabine                 687
Portao_Embarque          2
dtype: int64

In [66]:
dados_3['Portao_Embarque'].ffill(inplace=True)
dados_3.isnull().sum()

Sobreviveu               0
Classe                   0
Nome                     0
Sexo                     0
Idade                  177
Membros_Familia          0
Pais_Filhos_a_Bordo      0
Bilhete                  0
Valor_Passagem           0
Cabine                 687
Portao_Embarque          0
dtype: int64